#!/usr/bin/perl

use strict;
use warnings;

my $cpus = `lscpu | grep "CPU(s):" | head -1 | awk '{print \$NF}'`;
$cpus = $cpus - 1;

my $first = 1;

print "{\n";
print "\t\"data\":[\n";

foreach my $cpu (`seq 0 $cpus`)
{
   chomp $cpu;

   print "\t,\n" if not $first;
   $first = 0;

   print "\t{\n";
   print "\t\t\"{#CPUID}\":\"$cpu\"\n";
   print "\t}\n";
}

print "\t]\n";
print "}\n";
