#!/usr/bin/perl

use strict;
use warnings;

unless(-x "/usr/sbin/drbd-overview") {
   print "{\n";
   print "\t\"data\":[]\n";
   print "}\n";
   exit
}

my ($count) = 0;
my ($line);

print "{\n";
print "\t\"data\":[\n";

open DRBD,"sudo /usr/sbin/drbd-overview |" or exit 1;
while (<DRBD>) {
   $count++;
   $line = $_;

   if ($count > 1) {
      print "\t,\n";
   }

   my (@drbd) = ($line =~ m/\w+/g);

   print "\t{\n";
   print "\t\t\"{#DRBDID}\":\"" . $drbd[0] . "\",\n";
   print "\t\t\"{#DRBDRESOURCE}\":\"" . $drbd[1] . "\"\n";
   print "\t}\n";
}
close DRBD;

print "\t]\n";
print "}\n";
