#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use JSON::Parse 'parse_json';
use LWP::UserAgent;
use Data::Dumper;

my $url = "http://127.0.0.1:9200/_status";
my $help;

usage() if (!GetOptions(
    'url=s' => \$url,
    'help!' => \$help,
) or defined $help);

sub usage
{
    print "Unknown option: @_\n" if ( @_ );
    print "Usage: $0 [--url <STATUS_URL>] [--help]\n";

    exit;
}

my $ua = LWP::UserAgent->new(timeout => 15);
my $response = $ua->request(HTTP::Request->new('GET', $url));
if (!$response->is_success) {
    exit 1;
}

my $data = parse_json($response->content);
if (not defined $data) {
	exit 2;
}

print "- elasticsearch.shards.total $data->{_shards}{total}\n";
print "- elasticsearch.shards.successfull $data->{_shards}{successful}\n";
print "- elasticsearch.shards.failed $data->{_shards}{failed}\n";

my $indices = 0;
my $size = 0;

foreach my $index (keys %{$data->{indices}})
{
	$indices++;
	$size += $data->{indices}{$index}{index}{size_in_bytes};

	print "- elasticsearch.index.size[$index] $data->{indices}{$index}{index}{size_in_bytes}\n";
}

print "- elasticsearch.indices.total $indices\n";
print "- elasticsearch.indices.size $size\n";