#!/bin/sh

ZABBIX_SENDER=/usr/bin/zabbix_sender
ZABBIX_CONF=/etc/zabbix/zabbix_agentd.conf

ELASTICSEARCH_URL="http://127.0.0.1:9200/_status"

CONFIG_FILE=/etc/zabbix/scripts/trapper/elasticsearch.conf

[ -r "$CONFIG_FILE" ] && . $CONFIG_FILE

zsendall () {
	echo "$1"|$ZABBIX_SENDER -c $ZABBIX_CONF -i - 2>&1 >/dev/null
}

RET=$(/etc/zabbix/scripts/elasticsearch --url $ELASTICSEARCH_URL)
if [ "$?" -ne "0" ]; then
   exit 1
fi

zsendall "$RET"
